/**
 * Created by abbeymart on 2016-02-04.
 * fr-FR locales for mConnect UI labels /texts
 */

const frFRLabels = {
    solution              : 'Solution',
    packageGroup          : 'Package Group',
    package               : 'Package',
    task                  : 'Task (Function)',
    lang                  : 'World Languages',
    userLang              : 'Preferred Language',
    langList              : 'Language List',
    langDetail            : 'Language Details',
    types                 : 'Standard Types',
    typeList              : 'Standard Types List',
    typeDetail            : 'Standard Type Detail',
    category              : 'Categories',
    categoryList          : 'Categories List',
    categoryDetail        : 'Category Detail',
    subTitle              : 'Sub-Title (Slogan)',
    langSubMenuTitle      : 'Localization',
    langSubMenuTitle1     : 'Labels',
    langSubMenuTitle2     : 'Contents',
    langCode              : 'Language Code',
    langName              : 'Language Name',
    label                 : 'Labels',
    labelList             : 'Label List',
    labelDetail           : 'Label Details',
    bookItem              : 'Bookmark',
    bookmark              : 'Bookmark/Favourite',
    bookmarks             : 'Bookmarks/Favourites',
    bookmarkList          : 'Bookmarks/Favourites List',
    bookmarkDetail        : 'Bookmark/Favourite Details',
    content               : 'Content',
    contents              : 'Contents: page, post, blog etc.',
    contentList           : 'Contents List',
    contentDetail         : 'Content Details',
    contentDesc           : 'Content Information here...',
    message               : 'Message',
    priorMessage          : 'Prior Message(s)',
    location              : 'Location',
    locations             : 'Locations',
    locationList          : 'Locations List',
    locationDetail        : 'Location Details',
    locationView          : 'Location Details View',
    locationType          : 'Location Type',
    locationCode          : 'Location Code',
    stdCat                : 'Standard Category',
    stdCatList            : 'Standard Categories List',
    stdCatDetail          : 'Standard Category Details',
    catSubMenuTitle       : 'Codes (Types)',
    stdCodeName           : 'Standard Codes Name',
    stdCode               : 'Standard Codes',
    stdCodeList           : 'Standard Codes List',
    stdCodeDetail         : 'Standard Code Details',
    convert               : 'Conversions',
    convertList           : 'Conversions List',
    convertDetail         : 'Conversion Details',
    raaci                 : 'Responsibility Assignment',
    raaciList             : 'Responsibility Assignment List',
    raaciDetail           : 'Responsibility Assignment Details',
    service               : 'Solutions Portfolio',
    serviceList           : 'Solutions Portfolio List',
    serviceDetail         : 'Solution Component Details',
    serviceView           : 'Service Details View',
    user                  : 'User Administration',
    userList              : 'Users List',
    userDetail            : 'User Details',
    userView              : 'User Details View',
    personView            : 'Person Details View',
    userNew               : 'Login | Register | Recover',
    userLogin             : 'Login | Sign-in',
    userLogout            : 'Logout | Sign-out',
    userRegister          : 'Register new user account',
    userRecover           : 'Recover user login information',
    userRole              : 'Set Default Role',
    userAccount           : 'Users Account Management',
    myAccount             : 'My Account',
    userName              : 'Username',
    userProfile           : 'Account Profile',
    myAddress             : 'My Addresses',
    myPhone               : 'My Phones',
    address               : 'Addresses',
    addressMain           : 'Main Address',
    phoneMain             : 'Main Phone',
    addresses             : 'Addresses',
    addressList           : 'Addresses List',
    addressDetail         : 'Address Details',
    phone                 : 'Phones',
    phoneList             : 'Phones List',
    phoneDetail           : 'Phone Details',
    contact               : 'Contacts',
    contactList           : 'Contacts List',
    contactDetail         : 'Contact Details',
    doc                   : 'Document',
    docs                  : 'Documents',
    docList               : 'Documents List',
    docDetail             : 'Document Details',
    docName               : 'Document Name',
    docType               : 'Document Type',
    fileName              : 'File Name',
    fileCount             : 'Number of files may not exceed 10',
    fileSize              : 'Size of files may not exceed 10MB',
    fileType              : 'Only images (jpeg, png) and application (doc, xls, ppt, pdf...) are permitted',
    folder                : 'Folder',
    folders               : 'Folders',
    folderList            : 'Folders List',
    folderDetail          : 'Folder Details',
    docSetting            : 'Document Settings',
    docSettingList        : 'Document Settings List',
    docSettingDetail      : 'Document Setting Details',
    org                   : 'Organization',
    orgs                  : 'Organizations',
    orgList               : 'Organization List',
    orgDetail             : 'Organization Details',
    orgView               : 'Organization Details View',
    role                  : 'Role/Job',
    roles                 : 'Roles & Assignments',
    roleList              : 'Roles List',
    roleDetail            : 'Role Assignment Details',
    newUserSetting        : 'New User Setting',
    newAppSetting         : 'New System Setting',
    userSetting           : 'User Setting',
    appSetting            : 'System Setting',
    setting               : 'Settings Information',
    settingList           : 'Settings List',
    settingDetail         : 'Setting Details',
    eman                  : 'Errors Management',
    emanList              : 'Errors List',
    emanDetail            : 'Error',
    grant                 : 'Grants',
    grantTitle            : 'Grants (User-Role Assignments)',
    grantList             : 'Grants List',
    grantDetail           : 'Grant Roles to Users',
    grantSubMenuTitle     : 'Grant Role',
    grantSubMenuTitle1    : 'User Roles List',
    grantSubMenuTitle2    : 'User Roles Setup',
    todo                  : 'Action Items (Todos) Information',
    todoList              : 'Action Items (Todos) List',
    todoDetail            : 'Action Item (Todo) Details',
    remark                : 'Remarks / Updates',
    assignTo              : 'Assigned To',
    assignResource        : 'Resource Assignment',
    assignList            : 'Resource Assignments List',
    assignDetail          : 'Resource Assignment Details',
    support               : 'Support Services',
    supportList           : 'Support Services List',
    supportDetail         : 'Support Item Details',
    tax                   : 'Taxes...',
    taxInfo               : 'Taxes Information',
    taxList               : 'Taxes List',
    taxDetail             : 'Tax Details',
    taxNew                : 'New Tax Item',
    taxCat                : 'Tax Category',
    taxGroup              : 'Tax Group',
    taxJuri               : 'Tax Jurisdiction',
    taxRate               : 'Tax Rate (%)',
    taxAmount             : 'Tax Amount (Fixed or Percentage)',
    taxUnit               : 'Tax Unit (# or %)',
    taxRangeFrom          : 'Tax Range From',
    taxRangeTo            : 'Tax Range To',
    taxLocation           : 'Tax Location',
    taxCity               : 'Tax City',
    taxState              : 'Tax State / Province',
    taxCountry            : 'Tax Country',
    taxRegion             : 'Tax Region',
    taxSales              : 'Sales Tax',
    taxProperty           : 'Property Tax',
    taxIncome             : 'Income Tax',
    taxBusiness           : 'Business Tax',
    taxImport             : 'Import Tax',
    fixedValue            : "Fixed Value(#)",
    percentValue          : "Percent Value(%)",
    discountBeforeTax     : 'Before Tax',
    discountAfterTax      : 'After Tax',
    discountBeforeAfterTax: 'Before or After Tax',
    applyDiscount         : 'Apply Discount',
    juri                  : 'Jurisdiction',
    amount                : 'Amount',
    amountPay             : 'Amount to Pay',
    payment               : 'Payment Method',
    payments              : 'Payments',
    payList               : 'Payments List',
    payNew                : 'New Payment',
    payDetail             : 'Payment Details',
    payProvider           : 'Payment Providers',
    payProviderList       : 'Payment Providers List',
    payProviderDetail     : 'Payment Provider Details',
    provider              : 'Provider',
    providerNew           : 'New Provider',
    payTest               : 'Test Payment',
    payOrder              : 'Process Payment | Order',
    currency              : 'Currency',
    payDate               : 'Payment Date',
    payAmount             : 'Amount Paid',
    payDue                : 'Payment Due',
    payCustomer           : 'Customer',
    payStatus             : 'Status',
    payType               : 'Payment Type',
    payTypeDesc           : 'Payment Type (Credit, Debit, Transfer...)',
    payEndPoint           : 'Provider Payment URL',
    payEnv                : 'Payment Environment (test, live...)',
    payAccess             : 'Payment Access Key',
    payLocale             : 'Payment Locale (Localization)',
    payOwner              : 'Seller / Service Provider',
    payMethod             : 'Payment Method',
    payAddress            : 'Billing Address',
    ship                  : 'Shipping',
    shipEstimate          : 'Shipping/Cost Estimate',
    ships                 : 'Shippings',
    shipList              : 'Shippings List',
    shipNew               : 'New Shipping',
    shipDetail            : 'Shipping Details',
    shipProvider          : 'Shipping Providers',
    shipProviderList      : 'Shipping Providers List',
    shipProviderDetail    : 'Shipping Provider Details',
    shipCost              : 'Shipping Costs',
    shipToCost            : 'Shipping/Delivery Cost',
    shipToMethod          : 'Shipping Method',
    shipCostList          : 'Shipping Costs List',
    shipCostDetail        : 'Shipping Cost Details',
    shipProviderNew       : 'New Provider',
    shipCostNew           : 'New Cost',
    shipOrderList         : 'Ship-Orders List',
    shipOrderDetail       : 'Ship-Order Detail',
    shipOrderNew          : 'New Ship-Order',
    shipBy                : 'Shipping Provider',
    shipTest              : 'Test Shipping',
    shipItems             : 'Shipped Items',
    shipDate              : 'Shipped Date',
    shipMethod            : 'Shipping Method / Destination',
    shipEst               : 'Shipping & Handling',
    shipTax               : 'Shipping Tax',
    shipToAddress         : 'Ship To Address',
    shipOrder             : 'Ship Order-Item(s)',
    shipTrack             : 'Shipping Tracking Number',
    itemTax               : 'Order-items tax',
    beforeTax             : 'Total Before Tax',
    taxEst                : 'Estimated Tax',
    shipType              : 'Shipping Type',
    shipDuration          : 'Shipping Duration (days)',
    shipTypeDesc          : 'Shipping Type (Fixed, Measure...)',
    shipEndPoint          : 'Shipping Provider URL',
    shipEnv               : 'Shipping Environment (test, live...)',
    shipAccess            : 'Shipping Access Key',
    shipLocale            : 'Shipping Locale (Localization)',
    shipAddress           : 'Shipping Address',
    shipAmount            : 'Shipping Cost',
    natural               : 'Natural',
    resource              : 'Resource',
    resources             : 'Resources',
    product               : 'Product',
    productInfo           : 'Product Information',
    products              : 'Products',
    productList           : 'Products List',
    productDetail         : 'Product Details',
    productView           : 'Product Details View',
    productCode           : 'Product Code',
    productName           : 'Product Name',
    productImage          : 'Product Image',
    productTag            : 'Product Tag',
    productFeature        : 'Product Feature',
    productFeatures       : 'Product Features',
    productFeatureList    : 'Product Features List',
    productFeatureDetail  : 'Product Feature Detail',
    productPrice          : 'Product Price',
    productPrices         : 'Product Prices',
    productPriceList      : 'Product Price List',
    productPriceDetail    : 'Product Price Detail',
    productDiscount       : 'Product Discount',
    productDiscounts      : 'Product Discounts',
    productDiscountList   : 'Product Discount List',
    productDiscountDetail : 'Product Discount Detail',
    productDoc            : 'Product Document',
    productDocs           : 'Product Documents',
    productDocList        : 'Product Documents List',
    productDocDetail      : 'Product Document Details',
    productReview         : 'Product Review',
    productReviews        : 'Product Reviews',
    productReviewList     : 'Product Reviews List',
    productReviewDetail   : 'Product Review Details',
    productRating         : 'Product Rating',
    productEmail          : 'Send Item Information',
    sellerRating          : 'Seller\'s Rating',
    shipRating            : 'Shipping Rating',
    valueRating           : 'Product Value Rating',
    priceRating           : 'Price Rating',
    price                 : 'Price',
    priceInfo             : 'Price Information',
    prices                : 'Prices',
    priceList             : 'Prices List',
    priceDetail           : 'Price Details',
    priceView             : 'Price Details View',
    document              : 'Document',
    documents             : 'Documents',
    documentList          : 'Documents List',
    documentDetail        : 'Document Details',
    documentView          : 'Document Details View',
    discount              : 'Discount',
    discounts             : 'Discounts',
    discountCode          : 'Discount Code',
    discountList          : 'Discounts List',
    discountDetail        : 'Discount Details',
    discountView          : 'Discount Details View',
    discountUnit          : 'Discount Unit (# or %)',
    feature               : 'Feature',
    features              : 'Features',
    featureList           : 'Discounts List',
    featureDetail         : 'Discount Details',
    featureView           : 'Discount Details View',
    inventories           : 'Inventories',
    inventory             : 'Inventory',
    inventoryList         : 'Inventory List',
    inventoryDetail       : 'Inventory Details',
    review                : 'Review',
    reviews               : 'Reviews',
    reviewList            : 'Reviews List',
    reviewDetail          : 'Review Details',
    keyword               : 'Keywords',
    printItem             : 'Print Page',
    sendItem              : 'Send to Email',
    shopCart              : 'Shopping Cart',
    shipFrom              : 'Ship From',
    shipTo                : 'Ship To',
    soldBy                : 'Sold By',
    inStock               : 'In Stock',
    image                 : 'Image',
    item                  : 'Item',
    itemSubTotal          : 'SubTotal For Items',
    costUnit              : 'Cost Unit',
    quantity              : 'Quantity',
    minQuantity           : 'Minimum Quantity',
    maxQuantity           : 'Maximum Quantity',
    sold                  : 'Item(s) Sold',
    trade                 : 'Trade',
    tradeDetail           : 'Trade Details',
    tradeUpdate           : 'Update / Change Trade Request',
    trading               : 'Trading',
    tradePay              : 'Trade Payment Selection',
    tradeItems            : 'Trade Items',
    tradeDiscount         : 'Trade Discount',
    tradePrice            : 'Trade Pricing',
    tradeTerm             : 'Trade Conditions (Terms)',
    market                : 'Market',
    markets               : 'Markets',
    marketplace           : 'Marketplace',
    marketplaces          : 'Marketplaces',
    amazon                : 'Amazon Marketplace',
    ebay                  : 'eBay Marketplace',
    clickbank             : 'ClickBank Marketplace',
    alibaba               : 'Alibaba Marketplace',
    avail                 : 'Available in Stock',
    cart                  : 'Cart',
    carts                 : 'Carts',
    cartsList             : 'Carts List',
    cartDetail            : 'Cart Details',
    cartView              : 'Shopping Cart',
    cartUpdate            : 'Cart Update',
    addCart               : 'Add-Item-to-Cart',
    listCart              : 'List-Cart-Items',
    addItem               : 'Add New Item',
    addWish               : 'Add-to-Wish',
    moveWish              : 'Move-to-Folder',
    checkout              : 'Proceed To Checkout',
    checkoutList          : 'Checkout List',
    checkoutDetail        : 'Checkout Details',
    wish                  : 'Wish',
    wishes                : 'Wishes',
    wishesList            : 'Wishes List',
    wishFolder            : 'Wish Folders',
    wishDetail            : 'Wish Details',
    wishName              : 'Wish Name',
    customer              : 'Customer',
    track                 : 'Tracking Code',
    order                 : 'Order',
    orders                : 'Orders',
    orderItem             : 'Order Item(s)',
    ordersList            : 'Orders List',
    orderDetail           : 'Order Details',
    orderName             : 'Order Name',
    orderNew              : 'New Order',
    orderCat              : 'Order Categories',
    orderCatList          : 'Order Categories List',
    orderCatDetail        : 'Order Category Detail',
    orderTotal            : 'Estimated Order Total',
    infoCat               : 'Information Categories',
    infoCatList           : 'Information Categories List',
    infoCatDetail         : 'Information Category Detail',
    subTotal              : 'SubTotal',
    orderSummary          : 'Order Summary',
    orderTax              : 'Order Tax',
    orderBeforeTax        : 'Order Total Before Tax',
    orderTotalTax         : 'Order Total + Tax',
    orderTotalCost        : 'Order Total Cost',
    orderPaid             : 'Amount Paid',
    orderTotalPaid        : 'Total Amount Paid',
    orderPayDue           : 'Amount Due',
    orderPayBalance       : 'Order Balance Amount',
    orderPay              : 'Order Payment',
    orderPays             : 'Order Payments',
    orderPaysList         : 'Order Payments List',
    orderPayDetail        : 'Order Payment Details',
    orderNumber           : 'Order Number',
    orderId               : 'Order ID',
    orderBy               : 'Order By',
    orderItems            : 'Order Items',
    orderDate             : 'Order Date',
    orderCancel           : 'Cancel Order',
    orderCancelType       : 'Cancel Type',
    orderCancelItem       : 'Cancel Order Item(s)',
    orderCancelList       : 'Cancelled Orders List',
    orderCancelDetail     : 'Cancel Order Detail',
    orderCancelled        : 'Cancelled Order',
    orderCancelledItem    : 'Cancelled Order Item(s)',
    orderReturns          : 'Returns',
    orderReturnsList      : 'Returns List',
    orderReturnDetail     : 'Return Detail',
    orderReturnItem       : 'Returned Order Item(s)',
    orderCancelAmount     : 'Cancelled Amount',
    orderReturnAmount     : 'Returned Amount',
    orderSaving           : 'Savings (Discount)',
    invoice               : 'Invoice',
    invoices              : 'Invoices',
    invoicesList          : 'Invoices List',
    invoiceDetail         : 'Invoice Details',
    receipt               : 'Receipt',
    receipts              : 'Receipts',
    receiptsList          : 'Receipts List',
    receiptDetail         : 'Receipt Detail',
    refund                : 'Refund',
    refunds               : 'Refunds',
    refundItem            : 'Refund Items List',
    refundsList           : 'Refunds List',
    refundDetail          : 'Refund Detail',
    refundable            : 'Refundable',
    refundAmount          : 'Refund Amount',
    refundPaid            : 'Total Refunded',
    refundDate            : 'Refund Date',
    refundMethod          : 'Refund Method',
    cancelDate            : 'Cancel Date',
    returnDate            : 'Return Date',
    method                : 'Method',
    total                 : 'Total',
    toRefund              : 'Refundable Amount',
    toPay                 : 'Payable Amount',
    campaign              : 'Campaign',
    campaigns             : 'Campaigns',
    tracking              : 'Tracking',
    report                : 'Report',
    reports               : 'Reports',
    policy                : 'Policy',
    policies              : 'Policies',
    policiesList          : 'Policies List',
    policyDetail          : 'Policy Details',
    policyRelation        : 'Policy Relation',
    pservice              : 'Policy-Services',
    pserviceList          : 'Policy-Services List',
    pserviceDetail        : 'Policy-Service Details',
    msg                   : 'Message',
    msgs                  : 'Messages',
    msgNew                : 'New Message',
    msgsList              : 'Messages List',
    msgDetail             : 'Message Details',
    msgRead               : 'Read/View Message',
    msgReply              : 'Reply a Message',
    msgsListNew           : 'New Messages (Unread)',
    msgsListInbox         : 'Inbox',
    msgsListDraft         : 'Draft Messages',
    msgsListSent          : 'Sent Messages',
    msgsListDeleted       : 'Deleted Messages',
    msgBody               : 'Message Content',
    msgFrom               : 'Message From (Email)',
    msgTo                 : 'Message To (Email)',
    msgSubject            : 'Message Subject (Title)',
    privacy               : 'Privacy',
    reply                 : 'Reply',
    read                  : 'Read',
    draft                 : 'Draft',
    audit                 : 'Audits Information',
    auditList             : 'Audits List',
    auditDetail           : 'Audit Details',
    auditListCreate       : 'Audits List (Create)',
    auditListUpdate       : 'Audits List (Update)',
    auditListAccess       : 'Audits List (Access)',
    auditListDelete       : 'Audits List (Delete)',
    auditListRead         : 'Audits List (Read)',
    coll                  : 'Collection',
    collValue             : 'Collection Values',
    oldValue              : 'Old Values',
    newValue              : 'New Values',
    keyValue              : 'Search Keywords',
    newItem               : 'New Item',
    new                   : 'New',
    createNew             : 'Create New Item',
    actionBy              : 'Action By',
    link                  : "Item link (URL)",
    homeLink              : 'Home',
    loginButton           : 'Login | Sign-in',
    regDate               : 'Registration Date',
    registerLink          : 'Register | Sign-Up',
    registerUserAccount   : 'Register User Account',
    updateUserAccount     : 'Update User Account',
    loginLink             : 'Login | Sign-in',
    loginName             : 'Login Name',
    emailUsername         : 'Email or Username',
    loginPassword         : 'Password',
    confirmPassword       : 'Confirm Password',
    rememberMe            : 'Remember Me',
    acceptTerm            : 'Accept Terms of Service',
    termService           : 'Terms of Service',
    activity              : 'Activity',
    actTab                : 'Activities',
    actLevelTab           : 'Levels',
    groupLevelTab         : 'Groups Delegation',
    groupUserTab          : 'Users Delegation',
    actTaskTab            : 'Tasks',
    act                   : 'Activities',
    actList               : 'Activities List',
    actDetail             : 'Activity Detail',
    actLevel              : 'Activity Levels Assignment',
    actLevelList          : 'Activity Levels List',
    actLevelDetail        : 'Activity Level Detail',
    actTask               : 'Activity Tasks',
    actTaskList           : 'Activity Tasks List',
    actTaskDetail         : 'Activity Task Detail',
    groupLevel            : 'Activity-Level Group Assignment',
    groupLevelList        : 'Activity-Level Groups List',
    groupLevelDetail      : 'Activity-Level Group Detail',
    groupUser             : 'Activity-Group User Assignment',
    groupUserList         : 'Activity-Group Users List',
    groupUserDetail       : 'Activity-Group User Detail',
    defaultGroup          : "Default Group/Role",
    otherGroup            : "Other Groups/Roles",
    actions               : 'Actions',
    action                : 'Action Item',
    actionType            : 'Action Type',
    actionDate            : 'Action Date',
    effort                : 'Effort',
    effortUnit            : 'Effort Measure (y/m/d/h/m)',
    assign                : 'Assignments',
    register              : 'Register',
    login                 : 'Login',
    logout                : 'Logout',
    recover               : 'Recover',
    verifyRequest         : 'Request Verification Email',
    recoverPassword       : 'Recover Password',
    resetPassword         : 'Reset Password',
    recoverUsername       : 'Recover Username',
    recoveryEmail         : 'Recovery Email',
    currentPassword       : 'Current Password',
    newPassword           : 'New Password',
    newUsername           : 'New Username',
    changePassword        : 'Change Password',
    changeUsername        : 'Change Username',
    changeEmail           : 'Change Email',
    changeRole            : 'Change Role',
    addEmail              : 'Add Email',
    profile               : 'Profile',
    utility               : 'Utilities',
    firstName             : 'First Name',
    middleName            : 'Middle Name',
    lastName              : 'Last Name',
    birthDate             : 'Date of Birth',
    partOf                : 'Part Of',
    cityName              : 'City',
    stateName             : 'State / Province',
    countryName           : 'Country',
    regionName            : 'Region',
    store                 : 'Warehouse(Store)',
    cabinet               : 'Cabinet (Carousel)',
    shelve                : 'Shelve',
    city                  : 'City',
    state                 : 'State / Province',
    country               : 'Country',
    region                : 'Region',
    timezone              : 'Time Zone',
    from                  : 'From',
    to                    : 'To',
    default               : 'Default?',
    serviceItem           : 'Service Item',
    deactivate            : 'Deactivate',
    isCreate              : 'Create?',
    isRead                : 'Read?',
    isUpdate              : 'Update?',
    isDelete              : 'Delete?',
    organizations         : 'Organizations',
    orgNumber             : 'Bus Number',
    orgName               : 'Organization Name',
    orgStartDate          : 'Start Date',
    orgIndustry           : 'Industry',
    orgType               : 'Org type',
    startDate             : 'Start Date',
    endDate               : 'End Date',
    streetNumber          : 'Street Number',
    streetName            : 'Street Name',
    postalCode            : 'Postal Code',
    addressDesc           : 'Address Description',
    streetType            : 'Street Type',
    streetDirection       : 'Street Direction',
    addressCat            : 'Address Category',
    addressType           : 'Address Type',
    addressCity           : 'City',
    addressState          : 'State / Province',
    addressCountry        : 'Country',
    addressOwner          : 'Address Owner',
    phoneNumber           : 'Telephone Number',
    owner                 : 'Owner',
    tag                   : 'Content/Page Tag',
    path                  : 'Path (Tag)',
    title                 : 'Title',
    fixedCost             : 'Fixed Price',
    unitCost              : 'Unit Price',
    cost                  : 'Cost',
    costType              : 'Price Types (Fixed, Unit...)',
    priority              : 'Priority',
    low                   : 'Low',
    medium                : 'Medium',
    high                  : 'High',
    lat                   : 'Latitude',
    long                  : 'Longitude',
    select                : 'Select',
    isActive              : 'Active?',
    isCancel              : 'Cancel?',
    isTrade               : 'Trade-Point?',
    isTax                 : 'Taxable?',
    isAdmin               : 'Admin-User?',
    name                  : 'Name',
    fullName              : 'Full Name',
    email                 : 'Email Address',
    toEmail               : 'Send to Email',
    fromEmail             : 'Send from Email',
    subject               : 'Message Subject',
    desc                  : 'Description',
    save                  : 'Save',
    create                : 'Create',
    access                : 'Access Level',
    update                : 'Update',
    view                  : 'View',
    detail                : 'Details',
    remove                : 'Remove',
    delete                : 'Delete',
    saveForLater          : 'Save For Later',
    savedForLater         : 'Saved For Later',
    moveToCart            : 'Move To Cart',
    movedToCart           : 'Moved To Cart',
    undelete              : 'Undo Delete',
    send                  : 'Send',
    yes                   : 'Yes',
    no                    : 'No',
    code                  : 'Code',
    type                  : 'Type',
    list                  : 'List',
    itemsList             : 'Items List',
    itemsDelete           : 'Delete Selected Item(s)',
    like                  : 'Likelihood',
    impact                : 'Impact',
    labelItem             : 'Label',
    key                   : 'Key',
    attr                  : 'Attribute',
    value                 : 'Value',
    relation              : 'Relation',
    parent                : 'Part Of',
    measure               : 'Measure (Weight, Size...)',
    phoneCode             : 'Phone Code',
    cat                   : 'Category',
    cats                  : 'Categories',
    catList               : 'Category List',
    catDetail             : 'Category Details',
    catName               : 'Category Name',
    codeName              : 'Code Name',
    group                 : 'Group',
    scope                 : 'Scope',
    status                : 'Status',
    rating                : 'Rating',
    verifyUser            : 'Verify User Email',
    sendVerifyEmail       : 'Send Verification Email',
    backToList            : 'Back to the List page',
    mcHomeFooter          : 'MC Corporation - Solutions & Services',
    min                   : 'Minimum Value',
    max                   : 'Maximum Value',
    unit                  : 'Unit of Value',
    level                 : 'Delegation Level',
    buy                   : 'Buy',
    sell                  : 'Sell',
    seller                : 'Seller',
    request               : 'Request',
    inform                : 'Inform',
    contribute            : 'Contribute',
    recommend             : 'Recommend',
    approve               : 'Approve',
    env                   : 'Environment',
    welcome               : 'Welcome',
    solutions             : 'Solutions',
    documentation         : 'Documentation',
    fastLink              : 'Fast Links',
    mp                    : 'Marketplace',
    mpe                   : 'Marketplace Explorer',
    info                  : 'Information',
    int                   : 'Intelligence',
    advert                : 'Advertisement',
    adverts               : 'Advertisements',
    go                    : 'Go',
    search                : 'Search',
    searches              : 'Searches',
    searches_1            : 'Searches (services, products, organizations, places and people)',
    searchesList          : 'Searches List',
    searchResult          : 'Search Result',
    searchDetail          : 'Search Item Detail',
    services              : 'Services',
    people                : 'People',
    licTo                 : 'Licensed to',
    rightRes              : 'All Rights Reserved',
    website               : 'Website (e.g. mconnect.biz)',
    url                   : 'Item URL',
    urls                  : 'Websites Links (Favourites)',
    date                  : 'Date',
    time                  : 'Time',
    dateAdded             : 'Date Added',
    reason                : 'Reason',
    test                  : 'Testing Activities',
    testCentral           : 'Test Shared Services',
    testOM                : 'Test Order Management',
    testOrderMessage      : 'Test Order Message',
    testOrderCancelMessage: 'Test Order Cancel Message',
    testOrderReturnMessage: 'Test Order Return Message',
    testOrderPayMessage   : 'Test Order Payment Message',
    testOrderRefundMessage: 'Test Order Refund Message',
    testOrderShipMessage  : 'Test Order Ship Message',
    msgHello              : 'Hello',
    msgStartOrder         : 'Thanks for your order',
    msgContentOrder       : 'Please see the details of your recently placed order below',
    msgStartOrderPay      : 'Thanks for the payment made for your order',
    msgContentOrderPay    : 'Please see the details of your payment below',
    msgContentOrderCancel : 'Please see the details of your order-item(s) cancellation below',
    msgContentOrderReturn : 'Please see the details of your returned item(s) below',
    msgContentOrderRefund : 'Please see the details of your payment refund below',
    msgContentShipOrder   : 'Please see the detailed of your shipped item(s) below',
    msgFooterSignature    : 'With Regards',
    msgOrgName            : 'mConnect',
    msgOrgAddress         : '100 Haimer Avenue, Toronto, ON, M9V 4M8',
    msgOrgWebsite         : 'www.mconnect.biz',
    msgOrgPhone           : '1-647-382-9900',
    notRegistered         : 'Not Registered / Sign-Up?',
    forgotPassword        : 'Forgot Your Password?',
    forgotLoginName       : 'Forgot Your LoginName?',
    getLoginName          : 'Get Login Name',
    hasAccount            : 'Already have an account?',
    guestUser             : 'Guest'
};

module.exports = frFRLabels;
